const imgDefault = [
    {name: 'imgDefault1', value: 'https://i.ibb.co/X2RkKp1/character1.jpg'},
    {name: 'imgDefault2', value: 'https://i.ibb.co/gV6FDBC/character2.jpg'},
    {name: 'imgDefault3', value: 'https://i.ibb.co/LYbrpfX/character3.jpg'},
    {name: 'imgDefault19', value: 'https://i.ibb.co/1bJzXb2/terminator.jpg'},
    {name: 'imgDefault10', value: 'https://i.ibb.co/RC4whmn/character11.jpg'},
    {name: 'imgDefault17', value: 'https://i.ibb.co/gt8gF55/rambo.jpg'},
    {name: 'imgDefault9', value: 'https://i.ibb.co/QvszrnP/character10.jpg'},
    {name: 'imgDefault13', value: 'https://i.ibb.co/wLhwjZF/genie-will-smith.jpg'},
    {name: 'imgDefault5', value: 'https://i.ibb.co/NprhPgX/character5.jpg'},
    {name: 'imgDefault6', value: 'https://i.ibb.co/ckcf4gF/character6.jpg'},
    {name: 'imgDefault7', value: 'https://i.ibb.co/vwdHxPN/character8.jpg'},
    {name: 'imgDefault8', value: 'https://i.ibb.co/L9pZdKS/character9.jpg'},
    {name: 'imgDefault11', value: 'https://i.ibb.co/SXRrxb2/crash-bandicoot.jpg'},
    {name: 'imgDefault12', value: 'https://i.ibb.co/ccGZX6F/freddy-mercury.jpg'},
    {name: 'imgDefault14', value: 'https://i.ibb.co/2SHHSw7/gerald.jpg'},
    {name: 'imgDefault15', value: 'https://i.ibb.co/7Kx3VHs/loki.jpg'},
    {name: 'imgDefault16', value: 'https://i.ibb.co/zbMcyD9/michael-jackson.jpg'},
    {name: 'imgDefault18', value: 'https://i.ibb.co/QdwFjYm/robert-led-zeppelin.jpg'},
    {name: 'imgDefault20', value: 'https://i.ibb.co/R7fSn5y/therock.jpg'},
    {name: 'imgDefault21', value: 'https://i.ibb.co/BfP6X2d/thomas.jpg'},
    {name: 'imgDefault4', value: 'https://i.ibb.co/RNj6vnC/character4.jpg'},
    {name: 'imgDefaul22', value: 'https://i.ibb.co/yp98SqF/timothee.jpg'},
]

export default imgDefault;